"""
DGT Core - Core Components
Constants and shared components for the DGT system
"""

# Viewport Constants (Game Boy Parity)
TILE_SIZE_PIXELS = 8
VIEWPORT_WIDTH_PIXELS = 160
VIEWPORT_HEIGHT_PIXELS = 144
VIEWPORT_TILES_X = 20
VIEWPORT_TILES_Y = 18

# Display Scaling (4x for better visibility)
DISPLAY_SCALE = 4
DISPLAY_WIDTH_PIXELS = VIEWPORT_WIDTH_PIXELS * DISPLAY_SCALE
DISPLAY_HEIGHT_PIXELS = VIEWPORT_HEIGHT_PIXELS * DISPLAY_SCALE

# Core constants
TARGET_FPS = 60
FRAME_DELAY_MS = 1000 // TARGET_FPS

# Render layers
RENDER_LAYERS = None  # Will be set by graphics engine

# Color palette
COLOR_PALETTE = None  # Will be set by graphics engine

__all__ = [
    'TILE_SIZE_PIXELS', 'VIEWPORT_WIDTH_PIXELS', 'VIEWPORT_HEIGHT_PIXELS',
    'VIEWPORT_TILES_X', 'VIEWPORT_TILES_Y', 'DISPLAY_SCALE',
    'DISPLAY_WIDTH_PIXELS', 'DISPLAY_HEIGHT_PIXELS',
    'TARGET_FPS', 'FRAME_DELAY_MS', 'RENDER_LAYERS', 'COLOR_PALETTE'
]
